// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4DKY41FO_OuFBs901Egl4Z4HPk65rjiI',
    appId: '1:1066310834197:web:0a4e21f05cd21efa03961c',
    messagingSenderId: '1066310834197',
    projectId: 'authtutorial-9db86',
    authDomain: 'authtutorial-9db86.firebaseapp.com',
    storageBucket: 'authtutorial-9db86.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd5bv2JYpyiFNnMhFscwB9xMwf-kXMFDY',
    appId: '1:1066310834197:android:e95461f1cad64a9603961c',
    messagingSenderId: '1066310834197',
    projectId: 'authtutorial-9db86',
    storageBucket: 'authtutorial-9db86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlEeM4umBGgD_EwLzL-hyoQ2NSnp_y24',
    appId: '1:1066310834197:ios:9aa7227590d3a5f703961c',
    messagingSenderId: '1066310834197',
    projectId: 'authtutorial-9db86',
    storageBucket: 'authtutorial-9db86.appspot.com',
    iosBundleId: 'com.example.gmaillogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlEeM4umBGgD_EwLzL-hyoQ2NSnp_y24',
    appId: '1:1066310834197:ios:9aa7227590d3a5f703961c',
    messagingSenderId: '1066310834197',
    projectId: 'authtutorial-9db86',
    storageBucket: 'authtutorial-9db86.appspot.com',
    iosBundleId: 'com.example.gmaillogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4DKY41FO_OuFBs901Egl4Z4HPk65rjiI',
    appId: '1:1066310834197:web:7b3909884c0a524203961c',
    messagingSenderId: '1066310834197',
    projectId: 'authtutorial-9db86',
    authDomain: 'authtutorial-9db86.firebaseapp.com',
    storageBucket: 'authtutorial-9db86.appspot.com',
  );
}
